/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BillingAddress: typeof import('./../components/BillingAddress/index.vue')['default']
    CardInfoEdit: typeof import('./../components/CardInfoEdit/index.vue')['default']
    Certificate: typeof import('./../components/Certificate/index.vue')['default']
    ChangePayType: typeof import('./../components/ChangePayType/index.vue')['default']
    CurrentCard: typeof import('./../components/CurrentCard/index.vue')['default']
    Iconify: typeof import('./../components/Iconify/index.vue')['default']
    PaymentInfo: typeof import('./../components/PaymentInfo/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    To3dsModel: typeof import('./../components/To3dsModel/index.vue')['default']
    Toast: typeof import('./../components/Toast/index.vue')['default']
    ToKycModel: typeof import('./../components/ToKycModel/index.vue')['default']
    VueCountTo: typeof import('./../components/VueCountTo/index.vue')['default']
  }
}
