/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Iconify: typeof import('./../components/Iconify/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    To3dsModel: typeof import('./../components/To3dsModel/index.vue')['default']
    ToKycModel: typeof import('./../components/ToKycModel/index.vue')['default']
    VueCountTo: typeof import('./../components/VueCountTo/index.vue')['default']
  }
}
